# Generated by Django 5.1 on 2024-10-24 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_alter_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
