# Generated by Django 5.1 on 2024-10-24 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0009_remove_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
    ]
