# Generated by Django 5.1 on 2024-10-24 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
    ]
