# Generated by Django 5.1 on 2024-10-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images'),
        ),
    ]
