# Generated by Django 5.1 on 2024-10-24 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
